### ISSUE TITLE
Clarify membership application policy in readme

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/london-membership#37]
We seem to have quite a few people creating PRs to add themselves to the members list without ever having attended a business meeting (and I assume without filling in the membership form?).

I would suggest a good starting point to fix this is to add a couple of sentences to the main readme about the process to become a member so that it's immediately obvious when people go looking for more information.

Another idea might be to add a PR template which people have to fill in saying something like 'I've now filled in my application form (link) and attended business meetings on [fill in date] and [fill in date] so I am eligible to apply for membership and have therefore opened this PR' - essentially to make it a bit clearer in every way possible that there are steps.

Thoughts?

**Comment by claireinez** [comment]
The requirement to have attended two business meetings only applies to FAC10 onwards because we don't have attendance records for business meetings prior to those cohorts but you do raise a good point because there have been several people not following the exact process.

Perhaps we should do away with the application form in its current state altogether and instead make it into the PR template you suggest. That way we don't have to cross-reference a PR with a form, and people only have to make a PR in order to apply for membership, rather than also filling out a form.

**Comment by NataliaLKB** [comment]
I really like the PR template idea instead of a form! Excludes anyone using an GUI for git though 😬 . PR templates don't show up if you make the PR with one of those

**Comment by claireinez** [comment]
We could put it in the README and ask them to copy and paste?

**Comment by NataliaLKB** [comment]
@claireinez We can do both 😄 . The PR template will be good enough for 90% of people. I can probably do this on the weekend unless you have time sooner

**Comment by claireinez** [comment]
That would be great if you could do it @NataliaLKB, thanks!

**Comment by NataliaLKB** [comment]
Hey @claireinez, what should I do with the email address part of the form? I wouldn't expect people to add their email address, but I suppose we probably don't need it as we already have people's emails.

**Comment by claireinez** [comment]
Hmm good point. @sofer how necessary is the email address part?

**Comment by NataliaLKB** [comment]
> Hmm good point. @sofer how necessary is the email address part?

Discussed in person and it was decided this wasn't necessary to have in the form, so its not blocking.

**Comment by NataliaLKB** [comment]
Closing this as I think its better now. Please open if there is more clarification needed!
